name: shield_ai
description: "AI-Powered Fraud Detection for Mobile Money"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management and HTTP
  provider: ^6.1.2
  http: ^1.2.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  geolocator: ^14.0.2
  share_plus: ^12.0.1

  # Audio
  audioplayers: ^6.0.0

  # SVG rendering
  flutter_svg: ^2.0.10+1

  # Background tasks and local storage
  workmanager: ^0.9.0+3
  shared_preferences: ^2.2.3

  # Fonts and Icons
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

  # Markdown support
  flutter_markdown: ^0.7.1

  cupertino_icons: ^1.0.8
  process_run: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
